name: Run Tests and Generate Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure Pytest
      run: pip install allure-pytest

    - name: Run tests
      run: pytest --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report
      continue-on-error: true

    - name: Upload Allure Report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Allure Report artifact
      uses: actions/download-artifact@v2
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./allure-report
